CREATE TABLE PASSWORD_RESET_OTP (
    ID BIGINT IDENTITY(1,1) PRIMARY KEY,
    ACCOUNT_ID NCHAR(8) NOT NULL,
    EMAIL NVARCHAR(150) NOT NULL,
    OTP_CODE CHAR(6) NOT NULL,
    EXPIRES_AT DATETIME2 NOT NULL,
    USED BIT NOT NULL DEFAULT 0,
    USED_AT DATETIME2 NULL,
    CREATED_AT DATETIME2 NOT NULL DEFAULT SYSDATETIME()
);

CREATE INDEX IX_PASSWORD_RESET_OTP_ACCOUNT
ON PASSWORD_RESET_OTP (ACCOUNT_ID);

CREATE INDEX IX_PASSWORD_RESET_OTP_CODE
ON PASSWORD_RESET_OTP (OTP_CODE);

CREATE INDEX IX_PASSWORD_RESET_OTP_EXPIRES_AT
ON PASSWORD_RESET_OTP (EXPIRES_AT);

ALTER TABLE PASSWORD_RESET_OTP
ADD CONSTRAINT FK_PASSWORD_RESET_OTP_TAIKHOAN
FOREIGN KEY (ACCOUNT_ID)
REFERENCES TAIKHOAN(MA);
