ALTER TABLE MONHOC ADD IS_DELETED BIT NOT NULL CONSTRAINT DF_MONHOC_IS_DELETED DEFAULT 0;
ALTER TABLE SINHVIEN ADD IS_DELETED BIT NOT NULL CONSTRAINT DF_SINHVIEN_IS_DELETED DEFAULT 0;
ALTER TABLE GIAOVIEN ADD IS_DELETED BIT NOT NULL CONSTRAINT DF_GIAOVIEN_IS_DELETED DEFAULT 0;
ALTER TABLE BODE ADD IS_DELETED BIT NOT NULL CONSTRAINT DF_BODE_IS_DELETED DEFAULT 0;
